name = "ImprovedHagerZhangLinesearch"
uuid = "36e1a5ba-44f2-43dc-a7bf-508830393e4a"
authors = ["Mateusz Baran <mateuszbaran89@gmail.com>"]
version = "0.1.0"

[deps]
ManifoldsBase = "3362f125-f0bb-47a3-aa74-596ffd7ef2fb"
Manopt = "0fc0a36d-df90-57f3-8f93-d78a9fc72bb5"

[compat]
Manifolds = "0.9.11"
ManifoldsBase = "0.15"
Manopt = "0.4"
julia = "1.6"

[extras]
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Manifolds"]
